/* eslint-disable @typescript-eslint/no-require-imports */
/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: "class",
  content: [
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "surface-container-low": "#f5f3f3",
        "surface-bright": "#fbf9f8",
        "error-container": "#ffdad6",
        "primary-container": "#a9ba9d",
        "secondary-fixed-dim": "#e9c349",
        "on-tertiary": "#ffffff",
        "surface-variant": "#e4e2e2",
        primary: "#5A5F44",
        "surface-container": "#efeded",
        "on-primary-fixed-variant": "#3c4b34",
        "on-tertiary-fixed-variant": "#474744",
        "tertiary-container": "#b6b5b1",
        "on-surface": "#1b1c1c",
        "on-secondary-fixed-variant": "#574500",
        "on-primary-fixed": "#121f0c",
        "primary-fixed-dim": "#bbccae",
        "inverse-on-surface": "#f2f0f0",
        surface: "#fbf9f8",
        "surface-container-highest": "#e4e2e2",
        "on-secondary-container": "#745c00",
        outline: "#757870",
        "primary-fixed": "#d6e8c9",
        "surface-dim": "#dbd9d9",
        "secondary-fixed": "#ffe088",
        "inverse-primary": "#bbccae",
        "on-tertiary-container": "#464744",
        "inverse-surface": "#303030",
        "on-secondary-fixed": "#241a00",
        "on-primary": "#ffffff",
        "on-secondary": "#ffffff",
        background: "#fbf9f8",
        "surface-tint": "#5A5F44",
        "surface-container-lowest": "#ffffff",
        "tertiary-fixed": "#e4e2de",
        "secondary-container": "#fed65b",
        "on-error": "#ffffff",
        "surface-container-high": "#eae8e7",
        "on-surface-variant": "#444840",
        error: "#ba1a1a",
        tertiary: "#5e5e5c",
        "tertiary-fixed-dim": "#c8c6c3",
        "on-background": "#1b1c1c",
        "on-primary-container": "#3c4b34",
        "outline-variant": "#c5c8be",
        "on-error-container": "#93000a",
        "on-tertiary-fixed": "#1b1c1a",
        secondary: "#735c00",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        gutter: "24px",
        base: "8px",
        xl: "80px",
        xs: "4px",
        md: "24px",
        sm: "12px",
        "container-max": "1280px",
        lg: "48px",
      },
      fontFamily: {
        "headline-sm": ["var(--font-playfair)", "serif"],
        "body-md": ["var(--font-inter)", "sans-serif"],
        "body-lg": ["var(--font-inter)", "sans-serif"],
        "headline-md": ["var(--font-playfair)", "serif"],
        "display-lg-mobile": ["var(--font-playfair)", "serif"],
        "headline-md-mobile": ["var(--font-playfair)", "serif"],
        "label-md": ["var(--font-inter)", "sans-serif"],
        "label-sm": ["var(--font-inter)", "sans-serif"],
        "display-lg": ["var(--font-playfair)", "serif"],
      },
      fontSize: {
        "headline-sm": ["24px", { lineHeight: "1.4", fontWeight: "500" }],
        "body-md": ["16px", { lineHeight: "1.6", fontWeight: "400" }],
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
        "headline-md": ["32px", { lineHeight: "1.3", fontWeight: "600" }],
        "display-lg-mobile": ["32px", { lineHeight: "1.2", fontWeight: "700" }],
        "headline-md-mobile": ["24px", { lineHeight: "1.3", fontWeight: "600" }],
        "label-md": ["14px", { lineHeight: "1.2", letterSpacing: "0.05em", fontWeight: "500" }],
        "label-sm": ["12px", { lineHeight: "1.2", fontWeight: "600" }],
        "display-lg": ["48px", { lineHeight: "1.2", letterSpacing: "-0.02em", fontWeight: "700" }],
      },
      maxWidth: {
        "container-max": "1280px",
      },
      keyframes: {
        fadeInUp: {
          from: { opacity: "0", transform: "translateY(24px)" },
          to: { opacity: "1", transform: "translateY(0)" },
        },
        float: {
          "0%, 100%": { transform: "translateY(0)" },
          "50%": { transform: "translateY(-10px)" },
        },
      },
      animation: {
        "fade-in-up": "fadeInUp 0.7s ease-out both",
        float: "float 3s ease-in-out infinite",
      },
    },
  },
  plugins: [require("@tailwindcss/forms")],
};
